local History = require("kiro.history")

describe("kiro.history", function()
	before_each(function()
		History.clear()
	end)

	it("starts empty", function()
		assert.equals(0, History.size())
	end)

	it("adds messages to history", function()
		History.add("message 1")
		History.add("message 2")
		assert.equals(2, History.size())
	end)

	it("does not add duplicate consecutive messages", function()
		History.add("message 1")
		History.add("message 1")
		assert.equals(1, History.size())
	end)

	it("allows duplicate non-consecutive messages", function()
		History.add("message 1")
		History.add("message 2")
		History.add("message 1")
		assert.equals(3, History.size())
	end)

	it("navigates to previous messages", function()
		History.add("message 1")
		History.add("message 2")
		History.add("message 3")

		assert.equals("message 3", History.previous())
		assert.equals("message 2", History.previous())
		assert.equals("message 1", History.previous())
	end)

	it("stops at first message when going previous", function()
		History.add("message 1")
		History.add("message 2")

		History.previous()
		History.previous()
		assert.equals("message 1", History.previous())
	end)

	it("navigates to next messages", function()
		History.add("message 1")
		History.add("message 2")
		History.add("message 3")

		History.previous()
		History.previous()
		assert.equals("message 3", History.next())
	end)

	it("returns nil when at end of history", function()
		History.add("message 1")
		History.add("message 2")

		History.previous()
		History.previous()
		History.next()
		assert.is_nil(History.next())
	end)

	it("returns nil for next when no navigation started", function()
		History.add("message 1")
		assert.is_nil(History.next())
	end)

	it("returns all history", function()
		History.add("message 1")
		History.add("message 2")
		History.add("message 3")

		local all = History.get_all()
		assert.equals(3, #all)
		assert.equals("message 1", all[1])
		assert.equals("message 2", all[2])
		assert.equals("message 3", all[3])
	end)

	it("clears history", function()
		History.add("message 1")
		History.add("message 2")
		History.clear()
		assert.equals(0, History.size())
	end)

	it("respects max size", function()
		History.set_max_size(3)
		History.add("message 1")
		History.add("message 2")
		History.add("message 3")
		History.add("message 4")

		assert.equals(3, History.size())
		local all = History.get_all()
		assert.equals("message 2", all[1])
		assert.equals("message 4", all[3])
	end)

	it("trims history when max size is reduced", function()
		History.set_max_size(5)
		History.add("message 1")
		History.add("message 2")
		History.add("message 3")
		History.add("message 4")
		History.add("message 5")

		History.set_max_size(3)
		assert.equals(3, History.size())
		local all = History.get_all()
		assert.equals("message 3", all[1])
	end)

	it("resets navigation index when adding new message", function()
		History.add("message 1")
		History.add("message 2")

		History.previous()
		History.previous()

		History.add("message 3")
		assert.equals("message 3", History.previous())
	end)
end)
